version: '3.8'

services:
    ngrok:
        image: ngrok/ngrok:alpine
        container_name: ngrok
        environment:
            - NGROK_AUTHTOKEN
        command: 'tcp 25565'
        ports:
            - 4040:4040

    ngrok-sharer:
        container_name: ngrok_sharer
        image: wokcito/ngrok-sharer
        restart: unless-stopped
        environment:
            - NGROK_API_KEY
            - TELEGRAM_BOT_TOKEN
            - TELEGRAM_CHAT_ID
        depends_on:
            - ngrok
